# Generated by Django 4.1.5 on 2023-01-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество, шт.')),
                ('package_price', models.PositiveIntegerField(verbose_name='Стоимость заказа, коп.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_phone', models.CharField(max_length=13, verbose_name='Телефон покупателя')),
                ('total_order_cost', models.PositiveIntegerField(verbose_name='Общая стоимость корзины, коп.')),
                ('packages', models.ManyToManyField(related_name='package', to='store.package', verbose_name='Товары в корзину')),
            ],
            options={
                'verbose_name': 'Корзина заказов',
                'verbose_name_plural': 'Корзины заказов',
            },
        ),
    ]
