# Generated by Django 4.1.5 on 2023-01-29 22:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=13, verbose_name='Телефон покупателя')),
                ('customer_wishes', models.TextField(blank=True, null=True, verbose_name='Пожелания покупателя')),
                ('cart_sale', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Скидка на корзину, %')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Корзина заказов',
                'verbose_name_plural': 'Корзины заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество, шт.')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('sale', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Cкидка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказываемые товары',
                'verbose_name_plural': 'Заказываемые товары',
            },
        ),
        migrations.CreateModel(
            name='OrderItemCartRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order_item',
            field=models.ManyToManyField(related_name='orderitem', through='store.OrderItemCartRelations', to='store.orderitem', verbose_name='Заказ товара'),
        ),
    ]
