# Generated by Django 4.1.5 on 2023-01-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_price',
        ),
        migrations.AlterField(
            model_name='package',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество, шт.'),
        ),
    ]
