# Generated by Django 4.1.5 on 2023-01-20 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_orderitem_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sale',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Cкидка'),
        ),
    ]
