# Generated by Django 4.1.5 on 2023-01-20 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
        ('store', '0004_alter_orderitem_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина заказов', 'verbose_name_plural': 'Корзины заказов'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Детали заказа', 'verbose_name_plural': 'Детали заказа'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказываемые товары', 'verbose_name_plural': 'Заказываемые товары'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_item',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='Детали заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество, шт.'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_item',
            field=models.ManyToManyField(related_name='orderitem', to='store.orderitem', verbose_name='Заказ товара'),
        ),
    ]
