# Generated by Django 4.1.5 on 2023-01-23 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стоимость корзины, коп.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_sale',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Скидка на корзину, %'),
        ),
    ]
