# Generated by Django 4.1.5 on 2023-01-24 13:59

from django.db import migrations, models
import store.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_total_cost_alter_cart_cart_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consumer_phone',
            field=models.CharField(max_length=13, validators=[store.utils.ValidatePhone], verbose_name='Телефон покупателя'),
        ),
    ]
