# Generated by Django 4.1.5 on 2023-01-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_consumer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consumer_phone',
            field=models.CharField(max_length=13, verbose_name='Телефон покупателя'),
        ),
    ]
