# Generated by Django 4.1.5 on 2023-01-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
        ('store', '0009_remove_cart_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.order', verbose_name='Детали заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='Товар'),
        ),
    ]
