# Generated by Django 4.1.5 on 2023-01-27 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cart_is_completed_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
