# Generated by Django 4.1.5 on 2023-01-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cart_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_phone',
            field=models.CharField(default='+375296217433', max_length=13, verbose_name='Телефон покупателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_wishes',
            field=models.TextField(blank=True, null=True, verbose_name='Пожелания покупателя'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
