# Generated by Django 4.1.5 on 2023-01-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_cart_order_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
