# Generated by Django 4.1.5 on 2023-01-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cart_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID cессии'),
        ),
    ]
