# Generated by Django 4.1.5 on 2023-01-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cart_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
