# Generated by Django 4.1.5 on 2023-01-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producttypes_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(default=500, verbose_name='Cтоимость товара в коп.'),
            preserve_default=False,
        ),
    ]
