# Generated by Django 4.1.5 on 2023-01-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypes',
            name='slug',
            field=models.SlugField(default='slug-1', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
