# Generated by Django 4.1.5 on 2023-01-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producttypes_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ManyToManyField(related_name='products_type', to='products.producttypes', verbose_name='Тип товара'),
        ),
    ]
