# Generated by Django 4.1.5 on 2023-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ManyToManyField(related_name='product_type', to='products.producttypes', verbose_name='Тип товара'),
        ),
    ]
