# Generated by Django 4.1.5 on 2023-01-15 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Изоображениe категории'),
            preserve_default=False,
        ),
    ]
